import type { CSSProperties } from "react";

export const adminStyles = {
  page: {
    minHeight: "100svh",
    background: "#F6F8FB",
    color: "#363A3D",
    padding: 20,
  },
  shell: {
    width: "100%",
    maxWidth: 1120,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  panel: {
    background: "#ffffff",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    padding: 18,
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    margin: 0,
  },
  subtitle: {
    color: "#4b5563",
    fontSize: 14,
    margin: "4px 0 0",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: 14,
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 13,
    fontWeight: 700,
  },
  input: {
    minHeight: 42,
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    padding: "0 10px",
    fontSize: 16,
    background: "#ffffff",
  },
  textarea: {
    minHeight: 88,
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    background: "#ffffff",
    resize: "vertical",
  },
  button: {
    minHeight: 44,
    border: 0,
    borderRadius: 8,
    background: "#53C1ED",
    color: "#ffffff",
    fontSize: 15,
    fontWeight: 700,
    padding: "0 16px",
  },
  secondaryButton: {
    minHeight: 40,
    border: "1px solid #cbd5e1",
    borderRadius: 8,
    background: "#ffffff",
    color: "#363A3D",
    fontSize: 14,
    fontWeight: 700,
    padding: "0 12px",
  },
  dangerButton: {
    minHeight: 40,
    border: 0,
    borderRadius: 8,
    background: "#b91c1c",
    color: "#ffffff",
    fontSize: 14,
    fontWeight: 700,
    padding: "0 12px",
  },
  tableWrap: {
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 14,
  },
  th: {
    textAlign: "left",
    borderBottom: "1px solid #d1d5db",
    padding: "10px 8px",
    whiteSpace: "nowrap",
    background: "#f9fafb",
  },
  td: {
    borderBottom: "1px solid #e5e7eb",
    padding: "10px 8px",
    verticalAlign: "top",
    whiteSpace: "nowrap",
  },
  alert: {
    border: "1px solid #f59e0b",
    background: "#fffbeb",
    color: "#92400e",
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
  },
  success: {
    border: "1px solid #10b981",
    background: "#ecfdf5",
    color: "#065f46",
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
  },
} satisfies Record<string, CSSProperties>;
